name: spo_balaesang
version: 2.0.0+1
publish_to: none
description: Sistem presensi online kantor pemerintahan kecamatan balaesang.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  font_awesome_flutter: ^10.4.0
  flutter_cupertino_datetime_picker: ^3.0.0
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.3
  http: ^0.13.1
  provider: ^6.0.5
  intl: ^0.18.1
  url_launcher: ^6.0.4
  shared_preferences: ^2.0.5
  permission_handler: ^10.2.0
  slugify: ^2.0.0
  device_info: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  geolocator: ^9.0.2
#  android_intent: ^2.0.0
  app_settings: ^4.1.0
  flutter_config: any
  camera: ^0.10.5
  path_provider: ^2.0.1
  path: ^1.8.0
  flutter_image_compress: ^1.0.0
  qr_code_scanner: ^1.0.1
  flutter_countdown_timer: ^4.0.2
  image_picker: ^0.8.7+4
  geocoding: ^2.0.0
  progress_dialog: ^1.2.4
  shimmer: ^2.0.0-nullsafety.0
  get: ^4.1.1
  flare_flutter: ^3.0.0
  introduction_screen: ^3.1.8
  flutter_launcher_icons: ^0.13.1
  onesignal_flutter: ^3.5.1
  flutter_local_notifications: ^5.0.0
  cached_network_image: ^3.0.0
  photo_view: ^0.14.0
  flutter_native_splash: ^2.2.19
  flutter_spinkit: ^5.0.0
  lint: ^2.0.1
  pull_to_refresh: 2.0.0
  timeline_tile: 2.0.0
  search_page: ^2.3.0
  location: ^4.4.0
  flutter: 
    sdk: flutter
  flutter_dotenv: ^5.0.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path_ios: assets/launcher/icon.png
  image_path_android: assets/launcher/icon.png
  adaptive_icon_background: assets/launcher/launcher_bg.png
  adaptive_icon_foreground: assets/launcher/launcher_fg.png
  ios: true
  android: true

flutter_native_splash: 
  image: assets/launcher/icon.png
  color: 6b8eef
  android_disable_fullscreen: true

flutter: 
  assets:
    - assets/logo/
    - assets/flare/
    - assets/launcher/
  uses-material-design: true

